-- Foreign Key Constraints

-- Employees table
ALTER TABLE Dim_Employees_SCD1
ADD CONSTRAINT FK_Employees_ReportsTo
FOREIGN KEY (ReportsTo_SK) REFERENCES Dim_Employees_SCD1(EmployeeID_PK_SK);

-- Orders table
--ALTER TABLE Fact_Orders
--ADD CONSTRAINT FK_OrderDetails_OrderID
--FOREIGN KEY (OrderID) REFERENCES Orders(OrderID);

ALTER TABLE Fact_Orders
ADD CONSTRAINT FK_OrderDetails_ProductID
FOREIGN KEY (ProductID_SK) REFERENCES Dim_Products_SCD1(ProductID_PK_SK) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Fact_Orders
ADD CONSTRAINT FK_Orders_CustomerID
FOREIGN KEY (CustomerID_SK) REFERENCES Dim_Customers_SCD2(CustomerID_PK_SK) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Fact_Orders
ADD CONSTRAINT FK_Orders_EmployeeID
FOREIGN KEY (EmployeeID_SK) REFERENCES Dim_Employees_SCD1(EmployeeID_PK_SK) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Fact_Orders
ADD CONSTRAINT FK_Orders_ShipVia
FOREIGN KEY (ShipVia_SK) REFERENCES Dim_Shippers_SCD1(ShipperID_PK_SK) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Fact_Orders
ADD CONSTRAINT FK_Orders_TerritoryID
FOREIGN KEY (TerritoryID_SK) REFERENCES Dim_Territories_SCD1(TerritoryID_PK_SK) ON DELETE CASCADE ON UPDATE CASCADE;

-- Products table
ALTER TABLE Dim_Products_SCD1
ADD CONSTRAINT FK_Products_CategoryID
FOREIGN KEY (CategoryID_SK) REFERENCES Dim_Categories_SCD1(CategoryID_PK_SK) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Dim_Products_SCD1
ADD CONSTRAINT FK_Products_SupplierID
FOREIGN KEY (SupplierID_SK) REFERENCES Dim_Suppliers_SCD3(SupplierID_PK_SK) ON DELETE CASCADE ON UPDATE CASCADE;

-- Territories table
ALTER TABLE Dim_Territories_SCD1
ADD CONSTRAINT FK_Territories_RegionID
FOREIGN KEY (RegionID_SK) REFERENCES Dim_Region_SCD1(RegionID_SK_PK) ON DELETE CASCADE ON UPDATE CASCADE;
